jquast/blessed

blessed/formatters.py, blessed/keyboard.py, blessed/sequences.py
When running `tox` prospector complains about severael D211 violations:
pep257: D211 / No blank lines allowed before class docstring (found 1)
=> Fix prospector complains

tox.ini
fork() is dangerous, the test runner forks quite often
under dangerous circumstances -- our CI agents need to
stop immediately by default with basic arguments. For
developers who wish to see all errors, they may simply
run::
tox -epy27,py34 --
=> tox.ini: Use pytest -- -x unless -- is specified

blessed/formatters.py, blessed/keyboard.py, blessed/sequences.py, blessed/terminal.py, blessed/tests/test_formatters.py, blessed/tests/test_sequences.py
- sphinx nit: prefer ':arg' over ':param', creates briefer phrases and joins a few phrases
reducing LOC
- spellfix comment excersize -> exercise
=> Various docfix

blessed/sequences.py
Wasn't sure which way to change it, I made the docs match the code.
=> change docstring param name to name used in code

docs/intro.rst
Use:
```
.. code-block:: python
```
instead of `::` for code blocks, to enable syntax highlighting on github, as this file is used for the github readme.
=> Update intro.rst to enable syntax highlighting

.landscape.yml, .travis.yml, bin/display-maxcanon.py, bin/editor.py, bin/on_resize.py, bin/progress_bar.py, bin/worms.py, blessed/formatters.py, blessed/keyboard.py, blessed/sequences.py, blessed/terminal.py, blessed/tests/test_core.py, requirements-analysis.txt, setup.py, tox.ini
[Python 3.7](https://www.python.org/dev/peps/pep-0537/) is scheduled for release on June 15th so I've started testing some of my projects for compatibility. I ran into some issues running blessed due to changes in the the [re](https://docs.python.org/3.7/library/re.html) module. I also added 3.6 and 3.7 to tox and travis and included changes needed to ensure all the tests pass. Summary of the changes is below.
**Python 3.7 compatibility**
- [re.sub](https://docs.python.org/3.7/library/re.html#re.sub): Unknown escapes in repl consisting of '\' and an ASCII letter now are errors.
- blessed/sequences.py
- Workaround by making repl a function
`pattern = re.sub(r'\d+', _numeric_regex, _outp)`
becomes
`pattern = re.sub(r'\d+', lambda x: _numeric_regex, _outp)`
- …
=> Add support for Python 3.7

blessed/__init__.py, blessed/formatters.py, blessed/keyboard.py, blessed/terminal.py, blessed/tests/test_keyboard.py, blessed/win_terminal.py, requirements.txt, setup.py
This should address #18 and #90. (and maybe #73?)
This mostly came out of my efforts to support [Enlighten](https://pypi.org/project/enlighten) on Windows. I just needed a subset of Blessed for Enlighten, so that's what I originally implemented, but I kept looking at it and eventually it seemed like I had enough pieces to add Windows support to Blessed itself.
I decided to move the bulk of the logic to its own library, [Jinxed](https://pypi.org/project/jinxed). It provides a pure Python (with some ctypes calls) implementation for the parts of curses needed by Blessed. The terminfo is implemented through inherited dictionaries rather than by parsing the upstream terminfo. While that's a little more work upfront, it's more efficient and should make it easier for people to add new terminals. …
=> Add support for Windows

.gitignore, blessed/terminal.py, docs/further.rst
Just a few stray things:
- Corner case: Added `TypeError` as a caught exception for `_height_and_width()`. For Python 3, Jinxed uses `os.get_terminal_size()` to get the terminal size, and if it's not passed something like a file descriptor, as is the case with the PyCharm Python console, it will raise a TypeError.
- Corner case: locale.setlocale() has strange side effects with Python 2 on Windows. For example, printing `u'█'` works when the C locale is used, but, when the user default locale is used, it's printed as `'U'`. I couldn't find an good information on it and it seems to work fine in Python 3. The few code examples I could find skip setting locale on Windows.
- Tooling: Add .vscode to .gitignore. Purely for my benefit.
- Linting: Fixed some line lengths in the docs you updated …
=> Minor tweaks for Windows implementation

.travis.yml, bin/display-terminalinfo.py, blessed/terminal.py, blessed/tests/accessories.py, blessed/tests/test_core.py, blessed/tests/test_formatters.py, blessed/tests/test_keyboard.py, blessed/tests/test_length_sequence.py, blessed/tests/test_sequences.py, tox.ini
By manipulating our `@as_subprocess` test framework developed to execute tests in a sub-process to shield from the "cannot change terminal definition at runtime" issue -- for WIndows, no sub-process is used, and the `vtwin10` kind is always used.
We achieve 65% code coverage on Windows, and integrate into Travis-CI, passing below.
=> Run terminal tests on Windows 10 using Travis-CI

blessed/terminal.py, docs/history.rst, tests/test_length_sequence.py, tests/test_sequences.py
Prevent error condition, `ValueError: underlying buffer has been detached` from raising, Closes #126
=> bugfix: ValueError: underlying buffer has been detached

bin/colorchart.py, bin/editor.py, bin/keymatrix.py, bin/plasma.py, bin/progress_bar.py, bin/worms.py, bin/x11_colorpicker.py, blessed/terminal.py, docs/history.rst, docs/overview.rst, tests/accessories.py, tests/test_core.py, tests/test_length_sequence.py
=> Add and prefer Terminal.move_xy() over built-in 'move'

blessed/formatters.py, blessed/terminal.py, docs/history.rst, docs/overview.rst
Introduce this new kind of FormattingOtherString class, which allows us to make a capability that prints as a sequence, but is also callable as a capability to print another sequence, for the move_up/down/left/right() family of functions. A rather obscure convenience, Closes #47
=> term.move_up/down/left/right are now also callables

blessed/terminal.py, setup.py
For very lightweight environments, prefer terminal type 'dumb', and in case `TERM=`, that is, an empty string, also use phrase `dumb`, instead of `` or `unknown` as used previously, backporting  4e515462ba86483f6e8671bf42241fd39fd27c4e from https://github.com/erikrose/blessings/issues/39
=> Prefer 'dumb' over 'unknown' terminal type in lightweight environments

.travis.yml, blessed/_capabilities.py, blessed/color.py, blessed/keyboard.py, blessed/terminal.py, run_codecov.py, tox.ini
Update tests to fix a few issues:
- 3.9-dev was failing
- Only 3.8 tests were getting uploaded to codecov
- 2.6 workarounds were not being covered
- codecov can timeout on upload and doesn't include a retry option
=> Expand coverage analysis

tests/test_length_sequence.py
This test failure indicates to me that windows reads `does_styling` as False in travis,
so no URL is emitted, and that's ok for now
Since Windows 10 doesn't yet support hyperlinks, https://github.com/microsoft/terminal/issues/204
When it does, I think there is nothing for us to do, I think it works as-is before and after.
=> Do not test hyperlink sequences on windows / where does_styling is False

blessed/terminal.py, docs/history.rst, docs/intro.rst, docs/keyboard.rst, docs/project.rst, tests/test_full_keyboard.py, tox.ini
- `tox -e linkcheck`
- fix a few
- disable test on osx, fails.
```
def test_keystroke_0s_raw_input_ctrl_c():
"""0-second keystroke with raw allows receiving ^C."""
import pty
pid, master_fd = pty.fork()
if pid == 0:  # child
cov = init_subproc_coverage('test_keystroke_0s_raw_input_ctrl_c')
term = TestTerminal()
read_until_semaphore(sys.__stdin__.fileno(), semaphore=SEMAPHORE)
with term.raw():
os.write(sys.__stdout__.fileno(), RECV_SEMAPHORE)
inp = term.inkey(timeout=0)
os.write(sys.__stdout__.fileno(), inp.encode('latin1'))
if cov is not None:
cov.stop()
cov.save()
os._exit(0)
with echo_off(master_fd):
os.write(master_fd, SEND_SEMAPHORE)
read_until_semaphore(master_fd)
time.sleep(0.05)
>           os.write(master_fd, u'\x03'.encode('latin1'))
E           OSError: [Errno 5] Input/output …
```
=> Add 'linkcheck' tox target, fix a few, disable test broken on osx

.travis.yml, blessed/sequences.py, tests/test_sequences.py
Some minor optimizations for Sequence.length(). Should result in ~40% performance gain.
>>> from timeit import timeit
>>> 
>>> setup = """\
... from blessed import Terminal
... from blessed.sequences import Sequence
... term = Terminal()
... msg = term.clear + term.red(u'コンニチハ')
... """
>>> 
>>> timeit('Sequence(msg, term).length()', setup=setup, number=100000)
Before optimizations:
9.816482461988926
After optimizations:
5.693301688996144
There are some smaller optimizations, but the main one is using `padd()` instead of `strip_seqs()`. `strip_seqs()` was essentially calling `padd()` and then dropping any caps, so now `padd()` can take a boolean to drop caps as it's iterating. That saves a layer of function calls and half the calls to `iter_parse()`.
=> Optimize length

docs/keyboard.rst
Thanks for a great library! Experimenting with it now. Just found a typo in the docs, figured I'd fix it.
=> Fix typo in docs: keystrok -> keystroke

MANIFEST.in
Hi,
The current configuration is incomplete because a lot of doc files are
missing from PyPI, including conf.py.
It's weird because this had been fixed in blessings after https://github.com/erikrose/blessings/commit/af6b7b8773c2ff098bce112229913dee90928bfa
I am adding this package to Gentoo and we prefer relying on PyPI to fetch packages. Because of this issue, we will have to use GitHub's tarballs until this is fixed.
=> Include the whole doc folder in source distributions

docs/requirements.txt
Problem
-------
RTD does "pip install --upgrade sphinx<2" (...), before "pip install -r docs/requirements.txt", which says "already satisfied" in regards to "Sphinx". But `sphinx_paramlinks` since 0.4.0, is only compatible with `Sphinx>3`,
this line, https://github.com/sqlalchemyorg/sphinx-paramlinks/commit/3fab7d0964722ccc60b13073d019cf73df16ae83#diff-abe84b8e411ab7bd367ad033685b2b5dR31
raises `KeyError` for Sphinx less than version 3.
Solution
--------
freeze dependencies, to ensure successful RTD builds again. Also, add myself for notifications from RTD so that I get e-mail notified next time!
=> Fix sphinx build error on readthedocs.org

docs/examples.rst
This change corrects the link to the bounce.py file in the examples documentation.
=> update bounce.py link in examples

docs/intro.rst
Due to the line break emitted by the print statement the text doesn't appear at the bottom of the screen but one line above. Using end='' ensures the text appears at the bottom of the terminal window.
This took me a rather long time to figure out. :laughing:
=> Correct "bottom of the screen" example

blessed/terminal.py
If sys.__stdin__ is not set at all, the it will raise an "AttributeError" not a "ValueError".
Need to catch this as well.
=> Catch exception where stdin is not set

blessed/_capabilities.py, blessed/terminal.py, requirements.txt, tox.ini
This is to fix #202. Windows code pages are hard to detect in Python, so this will rely on the Windows API instead.
flake8_tests is failing, but it's unrelated and I think that's fixed in another pull request.
=> Use get_console_input_encoding for input encoding on Windows

blessed/terminal.py, blessed/win_terminal.py
Closes: #208 
Adds a `0.01` sec sleepto the windows version of the kbhit method as discussed in the linked issue.
I don't know if this could be an issue with other terminal emulators, but on cmd, Windows Terminal and conemu, increasing the sleep to `0.015` started making the following test script choppy, where it needed a bit of time until the buffer was fully printed out after the key was released and had inconsistent delays between each key being available. However, with the current `0.01` sec sleep the script functions as expected. 
I'm wary of relying on small differences like these making the desired impact and I'm wondering if it is some sort of sweet spot, but it seemed to work fine with the mentioned terminals I had at hand.
```py
import blessed
term = blessed.Terminal()
fl = True …
```
=> Add a small sleep to prevent high CPU usage in kbhit

.pylintrc, blessed/terminal.py, docs/history.rst, tests/accessories.py, tests/conftest.py, tests/test_core.py, tests/test_full_keyboard.py, tests/test_keyboard.py, tests/test_length_sequence.py, tests/test_sequences.py
- Consolidated number of times we check `platform.system() == 'Windows'`
- Updated history.rst
- Set current module so `Terminal` refs work
- Add entry for windows sleep in `kbhit()`
Once done, I think we need to push 1.19.0. There seems to be an issue with 1.18.1, https://github.com/jquast/blessed/issues/202#issuecomment-913857952
=> Prepare for 1.19.0

setup.py
Blocker for releasing 1.19.0
PyPI rejected upload because of unknown classifiers.
Should have caught this in 1.18.1, but I think I messed that one up by building from the wrong branch
=> Fix metadata formatting

blessed/formatters.pyi
Convert aliases into type annotations, as was intended.
This needs some work to prove it out, since apparently mypy isn't cross-checking the py and pyi files, or it would have caught this?
=> Fix global variable declarations in formatters.pyi

bin/cnn.py, bin/detect-multibyte.py, bin/editor.py, bin/plasma.py, bin/worms.py, blessed/colorspace.py, blessed/formatters.py, blessed/sequences.py, blessed/terminal.py, tests/test_formatters.py, tests/test_full_keyboard.py, tests/test_keyboard.py, tests/test_sequences.py, tests/test_wrap.py
**Pylint 2.14**
The main thing here is changing `width.__index__()` to `int(width)`. Pylint complained about the use of a dunder method and as I dug into it, using `int()` is more correct since it will support all the magic methods for coercion to an integer (`__int__()`, `__trunc__()`, etc). The test is explicitly for `__index__()` which exists in older Python versions, but is not invoked by `int()` until 3.8, so I limited the test to newer versions.
**Code Tweaks**
Pretty much all of these are getting rid of redundant syntax
- `{...}` instead of `set([...])` 
- `if cond` instead of `if not cond`
- `dict.get(item)` instead of `dict.get(item, None)`
=> Fixes for Pylint 2.14 and minor tweaks

.github/workflows/tests.yml
Small oversight on recent update that did show until today's scheduled tests
=> Fix for GitHub Actions

.github/workflows/tests.yml, bin/display-fpathconf.py, bin/tprint.py, bin/worms.py, blessed/formatters.py, blessed/terminal.py, docs/conf.py, docs/intro.rst, setup.py, tox.ini
Github dropped the Ubuntu 18.04 image we were using to test 3.4 and my distro doesn't have a package for it, so I think it's time to drop support.
If the query is correct, Blessed was only downloaded 509 times for Python 3.4 in the last 6 months.
This should fix the failing CI tests.
=> Drop 3.4 Support

bin/display-maxcanon.py, blessed/color.py, blessed/sequences.py, tests/test_sequences.py, tox.ini
- Fix docformatter issues failing in CI
- Gate `move_right()` in `truncate()` tests
- This address some of the failures in #251 
- Pin virtualenv for Tox
- virtualenv recently dropped support for 2.7 and 3.6
- This causes Tox to create a virtual environment with the pinned version and use it to create the tox environments
- This could potentially cause another issue down the road, but probably still worth it for now
=> June fixes

.github/workflows/tests.yml
Switched to a container (Debian 10 with 2.7.18) for 2.7 on Linux.
Dropped Python 2.7 for Windows. Containers only work for Linux runners. We could probably make it work by downloading and installing Python as a step. Looking at the download statistics, Windows users seem to use 3.8+, though there were ~6k downloads of Blessed for 2.7 on Windows last month. I'm just not sure I have the time to look into it.
Tox 4 supports syntax like py3.9 vs py39, so I was able to consolidate the test matrix a little. The older versions of Python get older versions of Tox, so they still need the old format.
=> Fixes for CI tests

.readthedocs.yml
Noticed Read the Docs builds are failing. We need to specify the OS. Unfortunately they haven't added support a latest tag on the OS yet.
I also moved the Python version to the new location and changed it to only specify the major version so it should use the latest supported.
I couldn't test this, but we could [enable PR builds in RTD](https://docs.readthedocs.io/en/stable/guides/pull-requests.html). Or add me as a maintainer in RTD and I'll do it.
=> Read the Docs configuration fixes

blessed/keyboard.py, blessed/terminal.py, tests/accessories.py, tests/test_core.py, tests/test_keyboard.py, tox.ini
Closes #158
Also pins docformatter due to related issue https://github.com/PyCQA/docformatter/issues/264
=> Implement ESCDELAY environment value

blessed/_capabilities.pyi, blessed/color.pyi, blessed/colorspace.pyi, blessed/formatters.pyi, blessed/keyboard.pyi, blessed/sequences.py, blessed/sequences.pyi, blessed/terminal.py, blessed/terminal.pyi, blessed/win_terminal.pyi
Pylint recently started checking .pyi files but there are some messages that either don't make sense (ex: unused argument) or aren't strictly necessary in a type hints file (ex: no function docstring).
There is some discussion in https://github.com/pylint-dev/pylint/issues/9096 of quieting these, but rather than wait, I figured we can fix the ones that made sense to fix and disable the others.
=> Pylint fixes for .pyi files

blessed/keyboard.pyi, blessed/terminal.py
Hopefully this takes care of the rest of the issues.
- Added type hints for `_time_left()`, `_read_until`, and `DEFAULT_ESCDELAY` in `keyboard.pyi`
- Removed `functools.partial()` in `Terminal.inkey()`
- Pylint complained about no return value
- It doesn't seem necessary anymore. I think at one point it consolidated some complicated code, but now these calls are pretty simple
- Ignore two cases where Pylint reported a false positive
=> Additional Pylint fixes

.github/workflows/tests.yml, .readthedocs.yml, bin/generate-x11-colorchart.py, docs/intro.rst, tox.ini
- Moves base Python for testing to 3.12
- Adds 3.13-dev
- Uses new image option for Read the Docs, ubuntu-lts-latest, so we always use the latest
- fixes small difference in Windows tag between intro and readme docs
=> Update Python versions in CI

.github/workflows/tests.yml, blessed/terminal.py, tests/accessories.py, tests/test_keyboard.py, tests/test_length_sequence.py
This fixes two issues causing the tests to fail:
1.) It seems PyPI updated their SSL config and the certs can't be verified by the version of pip included with 3.5. I've implemented a workaround to explicitly trust the necessary domains, only for 3.5 and only when installing Python. I thought about just pulling 3.5 instead, but I think we can wait until the next time something breaks. We're at 1173 downloads for 3.5 from PyPI in the last 6 months, 74 in the last 30 days (likely accelerated by this issue)
2.) Pylint recently introduced ``possibly-used-before-assignment``, which mostly flagged cases where we import a library like termios that doesn't exist on Windows. All the cases are guarded, but not always directly, so Pylint can't figure it out. Mostly I just disabled these in-line.
=> Test fixes June 2024

.github/workflows/tests.yml
I noticed after the last PR that a CodeCov report hadn't been generated. It looks like they haven't worked for a few months. It seems they are now requiring a token where previously it was optional. I also added the option to fail if codecov fails, which used to happen when we used the cli directly, but is disabled by default with the codecov action.
I also tried to update the action to V4, but that failed for 2.7 because the action (both V3 and V4) use a PyInstaller wrapped binary of the codecov-cli and one of the subcommands used in V4 is looking for a slightly newer version of glibc than the docker image for 2.7 provides. https://github.com/codecov/codecov-action/issues/1277
=> Add additional options to codecov-action

.github/workflows/tests.yml, bin/generate-keycodes.py, blessed/sequences.py, blessed/sequences.pyi, docs/conf.py, setup.py, tox.ini
A few housekeeping tasks
- Fix pylint errors that were breaking CI tests
- Too many positional arguments on ``Termcap.build()``
- Fix Sphinx issues that were breaking CI tests
- Deprecated behavior in conf.py
- ``csv-table`` used for keycodes now requires the deliminator in the header rather than a comma
- Update Python versions
- Default for testing switched to 3.13
- Added 3.14-pre as optional in CI
- Added logic to CI to use Codecov uploader version 4 except for Python 2.7, which uses version 3
- Maybe this will help with the random rate limit errors
- They released version 5 on November 14th, but it might be good to wait since they have done 7 bug releases since then
=> Housekeeping

.github/workflows/tests.yml
Looks like ubuntu-latest in GitHib Actions moved to 24.04, which dropped support for Python 3.7, so we have to pin it to use 22.04
=> Pin OS for Python 3.7 in CI

blessed/_compat.py, blessed/formatters.py, blessed/keyboard.py, blessed/sequences.py, requirements.txt, tests/accessories.py, tests/test_core.py, tests/test_full_keyboard.py, tests/test_keyboard.py, tests/test_length_sequence.py, tests/test_sequences.py
This is to address #281 in a more complete and performant way. We were only using six things from six (go figure):
- PY2
- unichr
- made this `unicode_chr` to avoid conflicts with the Python 2 builtin
- StringIO
- text_type
- Made this `TextType` to make the linter happy about class naming styles
- string_types
- This was either `(str, )` or `(basestring, )`, so I got rid of the tuples and called it `StringType`
- This seems to reduce the time `isinstance()` takes by ~40%
- six.moves.reload_module
`reload_module` logic was put in `test_core` since that's the only place it's used and we don't want to import things we don't need. The rest were put in `blessed._compat`
This should help Debian in their efforts, but it also gets rid of importing all of six when we only need a few things. The …
=> Drop six requirement

.github/workflows/tests.yml
Tests are currently failing because the OS image we were using for 3.5 and 3.6 has been removed. Initially I was going to work around this the way it was done for 2.7, pinning it to a Python container, but thought it would be better to just do everything (except Windows) in Python containers.
While Python containers do exist for Windows, Windows containers aren't supported in GitHub Actions, so Windows stays the same. Interestingly, the Windows images have multiple Python versions installed, so we don't even need the Python install task. Setting ``TOXPYTHON`` will do.
For the rest, they use ``python:{matrix.python-version}`` for the container unless it's specified. These docker images will get updated when new Python versions come out. For unsupported versions they remain static, but …
=> Use Python containers for Gitlab CI

.pylintrc, .readthedocs.yml, docs/requirements.txt, tests/test_length_sequence.py
- [Pylint bug](https://github.com/pylint-dev/pylint/issues/10418) counts entire file as duplicate code if ``.pyi`` file is present
- Set ``ignore-paths=.*.pyi`` in Pylint config as a workaround
- With Python 3.14, ``codec.open()`` raises a deprecation warning
- Added a conditional to cover Python 2
- Had to define ``open_`` or interpreter would complain local ``open`` wasn't defined
Read the Docs build failed on the first run because it couldn't find wcwidth. Not sure how it worked before, but fixed by pointing it to the requirements file in addition to the docs requirements file.
=> Minor fixes for failing tests

.github/workflows/tests.yml
This should workaround the flaky codecov uploads for Python 2.7 and 3.5. Those were stuck on an old version of the uploader because GLIBC is too old in the containers. This saves the coverage.xml for those jobs as artifacts, then uploads them in separate jobs running on ubuntu-latest.
=> Use a separate job to upload coverage for older python versions

blessed/sequences.py
Spend less time recomputing the length of characters by keeping a running length of the sequence
Test code:
```python
Terminal().wrap('a'*5000)
```
Profile before:
```
781279 function calls in 0.215 seconds
Ordered by: cumulative time
List reduced from 49 to 25 due to restriction <25>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000    0.215    0.215 terminal.py:1219(wrap)
1    0.000    0.000    0.215    0.215 textwrap.py:347(wrap)
1    0.000    0.000    0.214    0.214 sequences.py:146(_wrap_chunks)
5085    0.003    0.000    0.177    0.000 sequences.py:345(length)
5085    0.032    0.000    0.170    0.000 {built-in method builtins.sum}
62    0.005    0.000    0.140    0.002 sequences.py:192(_handle_long_word)
369747    0.083    0.000    0.138 …
```
=> wrap perf improvement when breaking long words

blessed/sequences.py, blessed/terminal.py, docs/history.rst
When a string includes a terminal escape sequence, Sequence.padd skips the early return from commit 8977680a
Test code:
```
import cProfile
import pstats
from blessed import Terminal
from blessed.sequences import Sequence
t = Terminal()
text = 'a'*5000 + t.restore
s = Sequence(text, t)
with cProfile.Profile() as pr: 
for _ in range(1000):
s.padd(strip=True)
p = pstats.Stats(pr)
p.strip_dirs().sort_stats('cumtime').print_stats(25)
```
Before profile with Python 3.12.3:
```
10002 function calls in 11.462 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1000   11.453    0.011   11.462    0.011 sequences.py:413(padd)
```
This branch strips all sequences (except horizontal ones) so that more strings can early return from padd.
This …
=> Optimize Sequence.padd for non-horizontal sequences
